title: Thomas Zühlke
description: Business Card Page
url: ''
baseurl: ''
profilepic: /images/tzuehlke.jpg
bkimage: /images/bk1.jpg
google_analytics: UA-XXXXXX-X
font_awesome: XXXXXXXXXX.js
author:
  name: Thomas Zühlke
  email: info@thomas-zuehlke.de
  twitter_username: thomzuehlke
  github_username: tzuehlke
  linkedin_username: thomas-zühlke-889182165
  meetup_name: Azure-Meetup-Rostock-MV
destination: _site
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  input: GFM
  hard_wrap: false
exclude:
  - README.md
  - screenshot-overview.png
